"""change name for URLMap

Revision ID: 210741dc4b07
Revises: 35d2591421fa
Create Date: 2023-06-27 12:33:10.789773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210741dc4b07'
down_revision = '35d2591421fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.String(length=2048), nullable=True),
    sa.Column('short', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('short')
    )
    op.drop_index('ix_url_model_timestamp', table_name='url_model')
    op.drop_table('url_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('short', sa.VARCHAR(length=16), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('short')
    )
    op.create_index('ix_url_model_timestamp', 'url_model', ['timestamp'], unique=False)
    op.drop_table('url_map')
    # ### end Alembic commands ###
